### PR TITLE
Fix an NPE caused by unchecked Bitmap.getConfig()

### PR DESCRIPTION
**Pull request by DavidEdwards**
This error was encountered with Crashlytics:

> Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
>        at android.graphics.Bitmap.createBitmap(Bitmap.java:825)
>        at android.graphics.Bitmap.createBitmap(Bitmap.java:802)
>        at android.graphics.Bitmap.createBitmap(Bitmap.java:769)
>        at com.google.android.libraries.cast.companionlibrary.utils.Utils.scaleAndCenterCropBitmap(SourceFile:364)
>        at com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$2.onPostExecute(SourceFile:1240)
>        at android.os.AsyncTask.finish(AsyncTask.java:632)
>        at android.os.AsyncTask.access$600(AsyncTask.java:177)
>        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>        at android.os.Handler.dispatchMessage(Handler.java:111)
>        at android.os.Looper.loop(Looper.java:194)
>        at android.app.ActivityThread.main(ActivityThread.java:5549)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

The source of the issue, is that `Bitmap.getConfig()` [can return null](http://developer.android.com/reference/android/graphics/Bitmap.html#getConfig()). 

In the CCL method `Utils.scaleAndCenterCropBitmap(...)` there is a method call to `Bitmap.createBitmap(newWidth, newHeight, source.getConfig());`. `source.getConfig()` is never checked prior to use.

### CODE REVIEW

**Comment by DavidEdwards** [comment]
Why should I have a CLA failure on this PR but not on my other PR? `cla/google — All necessary CLAs are signed`

**Comment by naddaf** [comment]
I don't know about the CLA stuff, but regarding the issue itself, do you have an image which returns null for config?

**Comment by DavidEdwards** [comment]
I don't personally have one as an example. 

It appeared through a crash log from my App. I cannot tell what the image was from itself. 

The crash is due to format of the Bitmap being unknown.

**Comment by naddaf** [comment]
I am more inclined to not exit if config is null but rather use, say, Bitmap.Config.ARGB_8888 for config (in createBitmap) when source.getConfig() returns null and wanted to test that first.

**Comment by DavidEdwards** [comment]
That is possibly worth a try. However, might it simply have a different error down the line when trying to decode a Bitmap using the wrong format?

**Comment by DavidEdwards** [comment]
Attempts with `Bitmap.Config.ARGB_8888` with my tests on pictures in my sample sets work fine.

**Comment by naddaf** [comment]
To begin with, the JavaDoc for createBitmap() doesn't say that config shouldn't be null, so that is one reason that I am not checking for that but if null throws an NPE, what I would do in the next update is:

1. if source.getConfig() returns null, I will use ARGB_8888
2. I  will wrap the createBitmap in a try-catch block and if it throws an exception or if the returns a null bitmap, I will exit early. 

These should provide a safe handling; I will probably make an update next week and will include my solution there.

**Comment by DavidEdwards** [comment]
Very well, I'll close this PR.

**Pull request closed without merging**
