### PR TITLE
Added support for Audio metadata

### PR DESCRIPTION
**Pull request by charly1811**
You can now specify the MediaMetadata type and also add Audio related metadata. A media type is specified using ```VideoCastManager.EXTRA_MEDIA_TYPE```

```
...
bundle.putInt(VideoCastManager.EXTRA_MEDIA_TYPE,TYPE);
...
```

If no media type is specified ```MediaMetadata.MEDIA_TYPE_MOVIE``` will be used instead

### CODE REVIEW

**Comment by charly1811** [comment]
I Signed it

**Comment by naddaf** [comment]
There are a number of issues with your pull request that I cannot accept. For example, I don't believe the layout (in landscape orientation) for the cast activity needs to be updated; clients can put their own layout there in their application if they desire to. Another one is to add wifi state permission to manifest; I prefer not to do that; clients can do that if they want to specially that the code that uses that permission (the ReconnectionService) is only used if the client enables the Wifi Reconnection and if one doesn't do that, there is no need for that permission. Feel free to open a feature request and tell me what exactly you need and I will see what I can do; it seems to me you want to have a way of setting the type of media to music.

**Comment by charly1811** [comment]
The thing is It is my first time to use pull requests and I made some kind of mistake. The commit I wanted to submit was [this one (4bef1e9)](https://github.com/charly1811/CastCompanionLibrary-android/commit/4bef1e9a9406112c7408764646de3a75b71c3d0b) and I included the other one by mistake. Sorry for that. 

My point was that VideoCastManager can be used for Video casting but also audio casting. This is why it could be a good idea to let the developer specify what type of media he or she is casting. That's why I modified the ```Utils.bundleToMediaInfo()``` method.

The ```Bundle``` passed it to can contains a value with the following key ```VideoCastManager.EXTRA_MEDIA_TYPE``` and the method will use its value as media type. If the ```Bundle``` does not contains this key it will use the default value (```MediaMetadata.MEDIA_TYPE_MOVIE```) instead

**Comment by naddaf** [comment]
Updating that method can be done but tell me why you need that? The type of media can be determined by what you put as the content type much more accurately so what exactly is the use case that you need this for?

**Comment by charly1811** [comment]
Even if the media content type is specified, some metadata will not be displayed because of the Media Type sent to the Cast device. For example let's consider the following media:

TiTLE=MY AUDIO
URL=http://my/audio/url.mp3
ARTIST=ME
ALBUM=MY SONGS

even tough the media will be played as an mp3 (Because of content type audio/mp3) the metadata ARTIST and ALBUM will not be displayed on the Cast device, because of the MediaType (MediaMetadata.MEDIA_TYPE_MOVIE)

**Comment by naddaf** [comment]
Ok, please open a feature request and I will get those fields done in the next update.

**Comment by charly1811** [comment]
Done: https://github.com/googlecast/CastCompanionLibrary-android/issues/242

**Pull request closed without merging**
